Models/TransactionType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TransactionRecord.Models
{
    public class TransactionType
    {
        public string TransactionTypeId { get; set; }

        public string Name { get; set; }

        public double? CommissionFee { get; set; }
    }
}

Controllers/TransactionController.cs
// Name: Arin Patodia
// Date: 09-12-2021
// Assignment #5 & Communication Activity


using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using TransactionRecord.Models;

namespace TransactionRecord.Controllers
{
    
    public class TransactionController : Controller
    {
        public TransactionController(TransactionDbContext txnContext)
        {
            _txnContext = txnContext;
        }

        public IActionResult OnlyTransactions(int id)
        {
            Company test = _txnContext.Companies.Where(d => d.CompanyId == id).FirstOrDefault();
            ViewBag.Name = test.CompanyName;
            ViewBag.Symbol = test.TickerSymbol;
            var alltransactions = _txnContext.Transactions.Include(h => h.Company).Include(h => h.TransactionType).Where(d => d.Company.CompanyId == id).ToList();
            return View(alltransactions);
        }

        // GET & POST for the Add sub-resource..
        [HttpGet()]
        public IActionResult Add()
        {
            ViewBag.Action = "Add";
            ViewBag.TransactionTypes = _txnContext.TransactionTypes.OrderBy(txnType => txnType.Name).ToList();
            return View("Edit", new Transaction());
        }

        [HttpPost()]
        public IActionResult Add(Transaction txn)
        {
            
            if (ModelState.IsValid)
            {
                _txnContext.Transactions.Add(txn);
                _txnContext.SaveChanges();

                return RedirectToAction("Index", "TransactionRecord");
            }
            else
            {
                ViewBag.Action = "Add";
                ViewBag.TransactionTypes = _txnContext.TransactionTypes.OrderBy(txnType => txnType.Name).ToList();

                
                return View("Edit", txn);
            }
        }








        // GET & POST for the Edit sub-resource..
        [HttpGet()]
        public IActionResult Edit(int id)
        {
            ViewBag.Action = "Edit";
            ViewBag.TransactionTypes = _txnContext.TransactionTypes.OrderBy(txnType => txnType.Name).ToList();
            var txn = _txnContext.Transactions.Find(id);
            return View(txn);
        }

        [HttpPost()]
        public IActionResult Edit(Transaction txn)
        {
            if (ModelState.IsValid)
            {
                _txnContext.Transactions.Update(txn);
                _txnContext.SaveChanges();
                this.TempData["LastActionMessage"] = $"{txn.Company.CompanyName} has been edited.";
                return RedirectToAction("Index", "TransactionRecord");
            }
            else
            {
                ViewBag.Action = "Edit";
                ViewBag.TransactionTypes = _txnContext.TransactionTypes.OrderBy(txnType => txnType.Name).ToList();
                return View(txn);
            }
        }










        // GET & POST for the Delete sub-resource..
        [HttpGet()]
        public IActionResult Delete(int id)
        {
            var txn = _txnContext.Transactions.Find(id);
            return View(txn);
        }

        [HttpPost()]
        public IActionResult Delete(Transaction txn)
        {
            _txnContext.Transactions.Remove(txn);
            _txnContext.SaveChanges();
            this.TempData["LastActionMessage"] = $"Successfully deleted.";
            return RedirectToAction("Index", "TransactionRecord");
        }

        





        private TransactionDbContext _txnContext;

    }
}

Controllers/TransactionNewController.cs
// Name: Arin Patodia
// Date: 09-12-2021
// Assignment #5 & Communication Activity


using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TransactionRecord.Models;

namespace TransactionRecord.Controllers
{
    public class TransactionNewController : Controller
    {
        private readonly TransactionDbContext _context;

        public TransactionNewController(TransactionDbContext context)
        {
            _context = context;
        }





        
        // GET: TransactionNew
        public async Task<IActionResult> Index()
        {
            var transactionDbContext = _context.Transactions.Include(t => t.Company).Include(t => t.TransactionType);
            return View(await transactionDbContext.ToListAsync());
        }

        // GET: TransactionNew/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var transaction = await _context.Transactions
                .Include(t => t.Company)
                .Include(t => t.TransactionType)
                .FirstOrDefaultAsync(m => m.TransactionId == id);
            if (transaction == null)
            {
                return NotFound();
            }

            return View(transaction);
        }

        // GET: TransactionNew/Create
        public IActionResult Create()
        {
            ViewData["CompanyId"] = new SelectList(_context.Companies, "CompanyId", "Address");
            ViewData["TransactionTypeId"] = new SelectList(_context.TransactionTypes, "TransactionTypeId", "TransactionTypeId");

            return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TransactionId,CompanyId,Quantity,SharePrice,TransactionTypeId")] Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                _context.Add(transaction);
                await _context.SaveChangesAsync();
                this.TempData["LastActionMessage"] = $"Successfully Created.";

                return RedirectToAction(nameof(Index));
            }
            ViewData["CompanyId"] = new SelectList(_context.Companies, "CompanyId", "Address", transaction.CompanyId);
            ViewData["TransactionTypeId"] = new SelectList(_context.TransactionTypes, "TransactionTypeId", "TransactionTypeId", transaction.TransactionTypeId);
            return View(transaction);
        }

        // GET: TransactionNew/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var transaction = await _context.Transactions.FindAsync(id);
            if (transaction == null)
            {
                return NotFound();
            }
            ViewData["CompanyId"] = new SelectList(_context.Companies, "CompanyId", "Address", transaction.CompanyId);
            ViewData["TransactionTypeId"] = new SelectList(_context.TransactionTypes, "TransactionTypeId", "TransactionTypeId", transaction.TransactionTypeId);
            return View(transaction);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TransactionId,CompanyId,Quantity,SharePrice,TransactionTypeId")] Transaction transaction)
        {
            if (id != transaction.TransactionId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(transaction);
                    this.TempData["LastActionMessage"] = $"Successfully Edited.";

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TransactionExists(transaction.TransactionId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CompanyId"] = new SelectList(_context.Companies, "CompanyId", "Address", transaction.CompanyId);
            ViewData["TransactionTypeId"] = new SelectList(_context.TransactionTypes, "TransactionTypeId", "TransactionTypeId", transaction.TransactionTypeId);
            return View(transaction);
        }

        // GET: TransactionNew/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var transaction = await _context.Transactions
                .Include(t => t.Company)
                .Include(t => t.TransactionType)
                .FirstOrDefaultAsync(m => m.TransactionId == id);
            if (transaction == null)
            {
                return NotFound();

            }

            return View(transaction);
        }

        // POST: TransactionNew/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var transaction = await _context.Transactions.FindAsync(id);
            _context.Transactions.Remove(transaction);
            await _context.SaveChangesAsync();
            this.TempData["LastActionMessage"] = $"Successfully Deleted.";

            return RedirectToAction(nameof(Index));
        }

        private bool TransactionExists(int id)
        {
            return _context.Transactions.Any(e => e.TransactionId == id);
        }
    }
}

Controllers/TransactionRecordController.cs
// Name: Arin Patodia
// Date: 09-12-2021
// Assignment #5 & Communication Activity


using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

using TransactionRecord.Models;

namespace TransactionRecord.Controllers
{
    public class TransactionRecordController : Controller
    {
        public TransactionRecordController(TransactionDbContext txnContext)
        {
            _txnContext = txnContext;
        }

        public IActionResult Index()
        {
            var txns = _txnContext.Transactions.Include(txn => txn.TransactionType).Include(txn => txn.Company).OrderBy(t => t.Company.TickerSymbol).ToList();
            return View(txns);
        }

        private TransactionDbContext _txnContext;
    }
}

Views/Transaction/Delete.cshtml
@model Transaction
@{
    ViewBag.Title = "Delete Transaction";
}

<h2>Confirm Deletion:</h2>
@*<h3>@Model.Quantity shares of @Model.Company.CompanyName (@Model.Company.TickerSymbol) - share price: @Model.SharePrice?.ToString("c2")</h3>*@

<form asp-action="Delete" method="post">
    <input type="hidden" asp-for="TransactionId" />
    <input type="hidden" asp-for="CompanyId" />

    <button type="submit" class="btn btn-primary">Delete</button>
    <a asp-controller="TransactionRecord" asp-action="Index" class="btn btn-primary">Cancel</a>
</form>

Views/Transaction/Edit.cshtml
@model Transaction
@{
    string title = ViewBag.Action + " Transaction";
    ViewBag.Title = title;
}

<h2>@title</h2>

<form asp-action="@ViewBag.Action" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="Company.TickerSymbol">Ticker symbol</label>
        <input asp-for="Company.TickerSymbol" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="TransactionTypeId">Transaction Type</label>
        <select asp-for="TransactionTypeId" class="form-control">
            <option value="">Select a transaction type..</option>
            @foreach (TransactionType txnType in ViewBag.TransactionTypes)
            {
                <option value="@txnType.TransactionTypeId">@txnType.Name</option>
            }
        </select>
    </div>

    <div class="form-group">
        <label asp-for="Company.CompanyName">Company name</label>
        <select asp-for="Company.CompanyName" class="form-control" asp-items="@ViewBag.CompanyName"></select> 
    </div>

    <div class="form-group">
        <label asp-for="Company.Address">Address</label>
        <input asp-for="Company.Address" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="Quantity">Quantity</label>
        <input asp-for="Quantity" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="SharePrice">Share price</label>
        <input asp-for="SharePrice" class="form-control">
    </div>

    <input type="hidden" asp-for="TransactionId" />

    <button type="submit" class="btn btn-primary">@ViewBag.Action</button>
    <a asp-controller="TransactionRecord" asp-action="Index" class="btn btn-primary">Cancel</a>
</form>

Views/Transaction/OnlyTransactions.cshtml
@model IEnumerable<TransactionRecord.Models.Transaction>

@{
    ViewData["Title"] = "Index";
}
@if (TempData.Keys.Contains("LastActionMessage"))
{
    <h4 class="alert-info">@TempData["LastActionMessage"]</h4>
}
<h2>@ViewBag.Name</h2>
<h2>@ViewBag.Symbol</h2>
<p>
    <a asp-controller="TransactionNew" asp-action="Create">Create New</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SharePrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Company)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TransactionType)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SharePrice)
                </td>
                <td>
                    <a asp-controller="TransactionNew" asp-action="Edit" asp-route-id="@item.CompanyId"> @Html.DisplayFor(modelItem => item.Company.CompanyName)</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TransactionType.TransactionTypeId)
                </td>
                <td>
                    <a asp-controller="TransactionNew" asp-action="Edit" asp-route-id="@item.CompanyId">Edit</a> |
                    <a asp-controller="TransactionNew" asp-action="Details" asp-route-id="@item.CompanyId">Details</a> |
                    <a asp-controller="TransactionNew" asp-action="Delete" asp-route-id="@item.CompanyId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>